project:
  type: website
  output-dir: output

website:
  title: "PECR Knowledge Hub"
  navbar:
    title: false
    logo: "./recursos/imagenes/generales/logo.svg"
    left:
      - href: index.qmd
        text: Home
      - text: Acerca de mi
        href: about.qmd

navbar:
  right:

format:
  html:
    theme: cosmo
    text-align: justify
    wrap: preserve
    css: "./recursos/estilos/styles_site.css"
    toc: false



