# Autogenerated by nbdev

d = { 'settings': { 'branch': 'principal',
                'doc_baseurl': '/PabloCaicedoR',
                'doc_host': 'https://PabloCaicedoR.github.io',
                'git_url': 'https://github.com/PabloCaicedoR/PabloCaicedoR',
                'lib_path': 'PabloCaicedoR'},
  'syms': {'PabloCaicedoR.core': {'PabloCaicedoR.core.foo': ('core.html#foo', 'PabloCaicedoR/core.py')}}}
